spring:
  application:
    name: mobile_compatible_payment_api

  datasource:
    url: jdbc:postgresql://localhost:5432/mobile_compatible_payment
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update


